### PR TITLE
don't log empty lines while crawling dirs

### LINKED ISSUE #837: [Bug]: Kadalu provisioner logs 8 empty lines every few seconds
**Describe the bug**
```
> k -n kadalu logs -f kadalu-csi-provisioner-0 -c kadalu-provisioner | cat -e
...
$
$
$
$
$
$
$
$
$
$
```

**To Reproduce**
1. Install v0.8.14 via releases manifests
2. Deploy Storage:
    ```
    apiVersion: kadalu-operator.storage/v1alpha1
    kind: KadaluStorage
    metadata:
      name: storage
      namespace: kadalu
    spec:
      pvReclaimPolicy: archive
      storage:
      - device: /dev/sda
        node: t5s-1
      - device: /dev/sda
        node: t5s-2
      - device: /dev/sda
        node: t5s-3
      type: Replica3
    ```
4. View logs `k -n kadalu logs -f kadalu-csi-provisioner-0 -c kadalu-provisioner`

**Expected behavior**
It should not print empty lines.

**Actual behavior**
It prints empty 8 lines consistently about every 5 seconds

**Environment:**
$ kubectl exec -it deploy/operator -n kadalu -- bash -c 'kubectl-kadalu version'
```
kubectl-kadalu plugin: 0.8.14
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-86pvs: 0.8.14
pod/kadalu-csi-nodeplugin-8vc4p: 0.8.14
pod/kadalu-csi-nodeplugin-zt94v: 0.8.14
pod/kadalu-csi-provisioner-0: 0.8.14
pod/operator-7579546f7-thrxm: 0.8.14
pod/server-storage-0-0: 0.8.14
pod/server-storage-1-0: 0.8.14
pod/server-storage-2-0: 0.8.14
```
 - Kadalu Version: 0.8.14
 - K8S_DIST: kubernetes

**Screenshots or Logs**
See above.

**Additional context**
Talos K8s cluster on 3 Raspberry Pi 4s

### PR DESCRIPTION
**Pull request by leelavg**
fixes: #837

Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>

### CODE REVIEW

File: csi/quota-crawler.sh [hunk 1]
```diff
@@ -6,37 +6,37 @@ echo "Starting the quota crawler script"
...
+    out=$(setfattr -n glusterfs.quota.total-usage -v ${used_size} $dir 2>&1)
     if ! [[ "$out" =~ "Operation not supported" ]]; then
-	echo "$out"
-	# This error comes most probably after a server pod
-	# restart or after a self-heal. This is a quick fix.
-	# Ideal fix is handling it in glusterfs code, but
-	# that would take time. In worst case, it would be
-	# a no-op as namespace would be already set.
-	out1=$(setfattr -n trusted.glusterfs.namespace -v "true" $dir 2>&1);
+      echo "$out" | awk 'NF'
```
Comment (leelavg) [inline csi/quota-crawler.sh:24]: - this is the only change, everything else was from `shfmt -i 2 -ci -w csi/quota-crawler.sh`

**Comment by leelavg** [comment]
- I didn't spin up a cluster for testing this change 😪 
- From the report, below points can be deducted
1. around every 5 sec 8 empty lines are logged --> in this script we have `sleep 5` in loop
2. log msg has no prefix --> no python file uses bare print, we use logf, so the msg seems to be from `echo`
3. every other echo follows text except this line which just prints var o/p

**Review by aravindavk — APPROVED** [review]

**Comment by amarts** [comment]
Looks like build is taking more time now. We may need tk increase the timeout in workflow files in that case. Not sure what changed from earlier for this delay.

**Review by vatsa287 — APPROVED** [review]
